import { Suspense } from 'react';
import PetDetailClient from './pet-detail-client';

import { Pet } from '@/types';

// Mock Data - same as home page
const mockPets: Record<string, Pet> = {
  '1': {
    id: '1',
    sellerId: 's1',
    sellerName: 'Paws & Claws Store',
    sellerLogo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller1',
    name: 'Golden Retriever Puppy',
    category: 'dogs',
    breed: 'Golden Retriever',
    price: 45000,
    stock: 3,
    description: 'Healthy and playful Golden Retriever puppy. This adorable pup is well-socialized, loves to play, and is great with children. Comes from a reputable breeder with excellent bloodlines. The puppy has been raised in a loving home environment and is ready to join your family.',
    images: ['https://images.unsplash.com/photo-1633722715463-d30628519d00?w=800&h=800&fit=crop'],
    age: '3 months',
    healthStatus: 'Excellent',
    gender: 'male',
    vaccinated: true,
    trained: false,
    status: 'active',
    views: 234,
    likes: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  '2': {
    id: '2',
    sellerId: 's2',
    sellerName: 'Pet Paradise',
    sellerLogo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller2',
    name: 'Persian Cat',
    category: 'cats',
    breed: 'Persian',
    price: 35000,
    stock: 2,
    description: 'Beautiful white Persian cat with stunning blue eyes. This elegant feline has a calm and gentle temperament, making it perfect for indoor living. Well-groomed with a luxurious coat that requires regular maintenance. Litter trained and very affectionate.',
    images: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=800&fit=crop'],
    age: '4 months',
    healthStatus: 'Excellent',
    gender: 'female',
    vaccinated: true,
    trained: true,
    status: 'active',
    views: 189,
    likes: 67,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  '3': {
    id: '3',
    sellerId: 's3',
    sellerName: 'Exotic Birds Hub',
    name: 'African Grey Parrot',
    category: 'birds',
    breed: 'African Grey',
    price: 85000,
    stock: 1,
    description: 'Intelligent talking parrot, hand-raised with excellent vocabulary. African Greys are known for their exceptional intelligence and ability to mimic human speech. This bird has been socialized from a young age and is comfortable around people. Comes with care instructions and dietary guidelines.',
    images: ['https://images.unsplash.com/photo-1444464666175-1642a9f33e12?w=800&h=800&fit=crop'],
    age: '1 year',
    healthStatus: 'Excellent',
    gender: 'male',
    vaccinated: true,
    trained: true,
    status: 'active',
    views: 456,
    likes: 123,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  '4': {
    id: '4',
    sellerId: 's1',
    sellerName: 'Paws & Claws Store',
    sellerLogo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller1',
    name: 'German Shepherd',
    category: 'dogs',
    breed: 'German Shepherd',
    price: 55000,
    stock: 2,
    description: 'Well-trained guard dog with excellent temperament. This German Shepherd is loyal, intelligent, and protective. Perfect for families looking for both a companion and a guardian. Has completed basic obedience training and responds well to commands.',
    images: ['https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=800&fit=crop'],
    age: '6 months',
    healthStatus: 'Excellent',
    gender: 'male',
    vaccinated: true,
    trained: true,
    status: 'active',
    views: 567,
    likes: 89,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  '5': {
    id: '5',
    sellerId: 's2',
    sellerName: 'Pet Paradise',
    sellerLogo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller2',
    name: 'Siamese Kitten',
    category: 'cats',
    breed: 'Siamese',
    price: 28000,
    stock: 4,
    description: 'Adorable Siamese kitten with striking blue eyes. Known for their vocal and social nature, Siamese cats make wonderful companions. This kitten is playful, curious, and loves attention. Has been raised with other cats and is very sociable.',
    images: ['https://images.unsplash.com/photo-1513360371669-4a0eb3a4b3e9?w=800&h=800&fit=crop'],
    age: '2 months',
    healthStatus: 'Excellent',
    gender: 'female',
    vaccinated: true,
    trained: false,
    status: 'active',
    views: 345,
    likes: 78,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  '6': {
    id: '6',
    sellerId: 's4',
    sellerName: 'Aqua World',
    sellerLogo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller4',
    name: 'Betta Fish',
    category: 'fish',
    breed: 'Betta Splendens',
    price: 1500,
    stock: 10,
    description: 'Colorful Betta fish with vibrant fins. These beautiful fish are easy to care for and make stunning additions to any aquarium. Each fish has unique coloring and personality. Comes with care instructions for optimal health.',
    images: ['https://images.unsplash.com/photo-1534080564897-61f3b9ad9a0e?w=800&h=800&fit=crop'],
    age: '6 months',
    healthStatus: 'Excellent',
    gender: 'male',
    vaccinated: false,
    trained: false,
    status: 'active',
    views: 123,
    likes: 34,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
};

export default async function PetDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const pet = mockPets[id];

  return (
    <Suspense fallback={<div>Loading...</div>}>
      <PetDetailClient pet={pet} />
    </Suspense>
  );
}
